#!/bin/bash
#
# Copyright (c) 2013 ADMB Foundation
#
args=
for arg in $*
do
  extension="${arg#*.}"
  if [ "-" = "${arg:0:1}" ]; then
    args="$args $arg"
  elif [ "$extension" = "$arg" ]; then
    args="$args ${arg}.cpp"
  else
    args="$args $arg"
  fi
done
admb -c $args
