all:\
 ADMBCodingStandards.html

all2:\
 ADMBContributeGuide.html\
 ADMBDesignModel.html\
 ADMBDevelopersGuide.html\
 ADMBDevelopersWorkshop2014.html\
 ADMBInfrastructure.html\
 ADMBIssueTracking.html\
 ADMBModelingLanguage.html\
 ADMBOrganizationChart.html\
 ADMBProjectPlan2014.html\
 ADMBReleaseProcedure.html\
 ADMBTestSuite.html\
 ADMBVersionControl.html

ADMBProjectPlan2014.html: ADMBProjectPlan2014.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBCodingStandards.html: ADMBCodingStandards.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBContributeGuide.html: ADMBContributeGuide.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBDesignModel.html: ADMBDesignModel.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBDevelopersGuide.html: ADMBDevelopersGuide.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBDevelopersWorkshop2014.html: ADMBDevelopersWorkshop2014.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBInfrastructure.html: ADMBInfrastructure.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBIssueTracking.html: ADMBIssueTracking.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBModelingLanguage.html: ADMBModelingLanguage.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBOrganizationChart.html: ADMBOrganizationChart.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBReleaseProcedure.html: ADMBReleaseProcedure.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBTestSuite.html: ADMBTestSuite.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

ADMBVersionControl.html: ADMBVersionControl.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@

resume.html: resume.txt
	cat begin.html>$@
	markdown_py $^>>$@
	cat end.html>>$@


clean:
	@rm -vf ADMBCodingStandards.html
	@rm -vf ADMBContributeGuide.html
	@rm -vf ADMBDesignModel.html
	@rm -vf ADMBDevelopersGuide.html
	@rm -vf ADMBDevelopersWorkshop2014.html
	@rm -vf ADMBInfrastructure.html
	@rm -vf ADMBIssueTracking.html
	@rm -vf ADMBModelingLanguage.html
	@rm -vf ADMBOrganizationChart.html
	@rm -vf ADMBProjectPlan2014.html
	@rm -vf ADMBReleaseProcedure.html
	@rm -vf ADMBTestSuite.html
	@rm -vf ADMBTesting.html
	@rm -vf ADMBVersionControl.html
