all:
	$(MAKE) --directory=catage
	$(MAKE) --directory=simple
	$(MAKE) --directory=forest

dev:
	$(MAKE) --directory=sdv

clean:
	$(MAKE) --directory=catage clean
	$(MAKE) --directory=simple clean
	$(MAKE) --directory=forest clean
	$(MAKE) --directory=sdv clean
