all:
	$(MAKE) --directory=catage
	$(MAKE) --directory=simple
	$(MAKE) --directory=forest

clean:
	$(MAKE) --directory=catage clean
	$(MAKE) --directory=simple clean
	$(MAKE) --directory=forest clean
	@rm -vf model_parameters/model_parameters.obj
