#!/bin/bash
shopt -s expand_aliases
alias help='echo -e "Usage: adlink [-d] [-g] [-r] [-s] model\n
Link AD Model Builder object code to executable.\n
  -d     Create DLL
  -g     Insert debugging symbols
  -r     Create ADMB-RE
  -s     Enforce safe bounds
  model  Filename prefix, e.g. simple\n"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "-help" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi

# Pop args until model=$1
adlib=-lado
unset re
s="-s "
unset shared
while getopts "dgrs" A; do
  case $A in
    d) shared="-shared ";;
    g) unset s;;
    r) re=true;;
    s) adlib=-lads;;
  esac
done
shift $[OPTIND-1]

if [ "`uname -s`" = "Darwin" ] ; then
  s=
fi

model="${1%.*}"

df1b2lib=-ldf1b2stub
if [[ -z $shared ]]; then out="-o $model"; else out="-o $model.so"; fi
if [[ $adlib == "-lado" ]]; then df1b2lib=-ldf1b2o; fi
if [[ $adlib == "-lads" ]]; then df1b2lib=-ldf1b2s; fi

ARG=
if test ! -z "${LDFLAGS}" ; then
  ARG="${LDFLAGS} "
fi

CMD="g++ -O3 ${s}${shared}-L$ADMB_HOME/lib $model.o $df1b2lib -ladmod -ladt $adlib $df1b2lib -ladmod -ladt $adlib ${ARG}$out"
printf "%s\n" "${CMD}"
eval ${CMD}

exit 0
