run:
	#@make -C b
	#@make -C bigmin
	@make -C hemholtz
	@make -C io_examp
	@make -C minimize
	#@make -C mixture
	#@make -C neural
	@make -C newt
	#@make -C robexamp
	@make -C simple
	@make -C struct
	#@make -C z
clean:
	#@make -C b clean
	#@make -C bigmin clean
	@make -C hemholtz clean
	@make -C io_examp clean
	@make -C minimize clean
	#@make -C mixture clean
	#@make -C neural clean
	@make -C newt clean
	#@make -C robexamp clean
	@make -C simple clean
	@make -C struct clean
	#@make -C z clean
