all:
	../../admb high_iarray.tpl
	./high_iarray
clean:
	@rm -vf admodel.cov
	@rm -vf admodel.dep
	@rm -vf admodel.hes
	@rm -vf eigv.rpt
	@rm -vf fmin.log
	@rm -vf high_iarray
	@rm -vf high_iarray.bar
	@rm -vf high_iarray.cor
	@rm -vf high_iarray.cpp
	@rm -vf high_iarray.eva
	@rm -vf high_iarray.htp
	@rm -vf high_iarray.log
	@rm -vf high_iarray.obj
	@rm -vf high_iarray.par
	@rm -vf high_iarray.std
	@rm -vf variance
