all:
	export ADMB_HOME=/Users/johnoel/Desktop/admb-trunk3/test/init_bounded_number_matrix/../../build/admb-macos10.6.3-xcode3.2.2-64bit/dist; export PATH=/Users/johnoel/Desktop/admb-trunk3/test/init_bounded_number_matrix/../../build/admb-macos10.6.3-xcode3.2.2-64bit/dist/bin:${PATH}; CXXFLAGS=-I/usr/local/gtest-1.5.0/include LDFLAGS="-L/usr/local/gtest-1.5.0/lib -lgtest" admb init_bounded_number_matrix

clean:
	rm -f admodel.cov
	rm -f admodel.dep
	rm -f admodel.hes
	rm -f eigv.rpt
	rm -f fmin.log
	rm -f init_bounded_number_matrix
	rm -f init_bounded_number_matrix.bar
	rm -f init_bounded_number_matrix.cor
	rm -f init_bounded_number_matrix.cpp
	rm -f init_bounded_number_matrix.eva
	rm -f init_bounded_number_matrix.htp
	rm -f init_bounded_number_matrix.log
	rm -f init_bounded_number_matrix.o
	rm -f init_bounded_number_matrix.par
	rm -f init_bounded_number_matrix.std
	rm -f variance
