verify: SS3 ham4 ham5 vonb vonbr simple

SS3:
	cd $(ADMB_HOME)\examples\admb\SS3
	makadmb SS3
	SS3
	cd $(ADMB_HOME)\examples\admb\SS3
	makadmbs SS3
	SS3

ham4:
	cd $(ADMB_HOME)\examples\admb\buscycle
	makadmb ham4
	ham4
	cd $(ADMB_HOME)\examples\admb\buscycle
	makadmbs ham4
	ham4

ham5:
	cd $(ADMB_HOME)\examples\admb\buscycle
	makadmb ham5
	ham5
	cd $(ADMB_HOME)\examples\admb\buscycle
	makadmbs ham5
	ham5

catage:
	cd $(ADMB_HOME)\examples\admb\catage
	makadmb catage
	catage
	cd $(ADMB_HOME)\examples\admb\catage
	makadmbs catage
	catage

chem-eng:
	cd $(ADMB_HOME)\examples\admb\chem-eng
	makadmb chem-eng
	chem-eng
	cd $(ADMB_HOME)\examples\admb\chem-eng
	makadmbs chem-eng
	chem-eng

finance:
	cd $(ADMB_HOME)\examples\admb\finance
	makadmb finance
	finance
	cd $(ADMB_HOME)\examples\admb\finance
	makadmbs finance
	finance

forest:
	cd $(ADMB_HOME)\examples\admb\forest
	makadmb forest
	forest
	cd $(ADMB_HOME)\examples\admb\forest
	makadmbs forest
	forest

pella-t:
	cd $(ADMB_HOME)\examples\admb\pella-t
	makadmb pella_t
	pella_t
	cd $(ADMB_HOME)\examples\admb\pella-t
	makadmbs pella_t
	pella_t

vonb:
	cd $(ADMB_HOME)\examples\admb\robreg
	makadmb vonb
	vonb
	cd $(ADMB_HOME)\examples\admb\robreg
	makadmbs vonb
	vonb

vonbr:
	cd $(ADMB_HOME)\examples\admb\robreg
	makadmb vonbr
	vonbr
	cd $(ADMB_HOME)\examples\admb\robreg
	makadmbs vonbr
	vonbr


simple:
	cd $(ADMB_HOME)\examples\admb\simple
	makadmb simple
	simple
	cd $(ADMB_HOME)\examples\admb\simple
	makadmbs simple
	simple

truncreg:
	cd $(ADMB_HOME)\examples\admb\truncreg
	makadmb truncreg
	runtrunc
	fruntrunc
	cd $(ADMB_HOME)\examples\admb\truncreg
	makadmbs truncreg
	runtrunc
	fruntrunc

n2mvol:
	cd $(ADMB_HOME)\examples\admb\vol
	makadmb n2mvol
	n2mvol
	cd $(ADMB_HOME)\examples\admb\vol
	makadmbs n2mvol
	n2mvol

union:
	cd $(ADMB_HOME)\examples\admb-re\union
	makadmb-re union
	union	
