all:
	autoconf --verbose --output=../../configure
	@printf "\nCreated configure.\n"
	@printf "To configure, type './configure'.\n"

clean:
	@rm -vrf autom4te.cache/
	@rm -vf configure
	@rm -vf autom4te.cache
	@rm -vf config.log
	@rm -vf admb.cfg.in
	@rm -vf config.status
