.PHONY: clean testminmax SS3 admb_messages init_bounded_number_matrix beta_regression hysimple simple_mcmc betareg gmrf RC04_solve RC04_det RC04_inv RC10_spline1 RC10_spline2 RC13_dsort RC15_eigen RC26_dflndet RC27_dfsolve1 RC27_dfsolve2 RC05_quad RC01_svd atan2

#all: clean beta_regression hysimple simple_mcmc betareg gmrf
#all: clean init_bounded_number_matrix admb_messages
all: clean atan2
#all: testminmax RC04_solve RC04_det RC04_inv RC10_spline1 RC10_spline2 RC13_dsort RC15_eigen RC26_dflndet RC27_dfsolve1 RC27_dfsolve2 RC05_quad RC01_svd

atan2:
	OPTIONS=-s make --directory=$@

testminmax:
	OPTIONS=-s make --directory=$@

SS3:
	OPTIONS=-s make --directory=$@

admb_messages:
	OPTIONS=-s make --directory=$@

init_bounded_number_matrix:
	OPTIONS=-s make --directory=$@

beta_regression:
	OPTIONS=-s make --directory=$@

hysimple:
	OPTIONS=-s make --directory=$@

simple_mcmc:
	OPTIONS=-s make --directory=$@

betareg:
	OPTIONS=-s make --directory=$@

gmrf:
	OPTIONS=-s make --directory=$@

RC04_solve:
	OPTIONS=-s make --directory=$@

RC04_det:
	OPTIONS=-s make --directory=$@

RC04_inv:
	OPTIONS=-s make --directory=$@

RC10_spline1:
	OPTIONS=-s make --directory=$@

RC10_spline2:
	OPTIONS=-s make --directory=$@

RC13_dsort:
	OPTIONS=-s make --directory=$@

RC15_eigen:
	OPTIONS=-s make --directory=$@

RC26_dflndet:
	OPTIONS=-s make --directory=$@

RC27_dfsolve1:
	OPTIONS=-s make --directory=$@

RC27_dfsolve2:
	OPTIONS=-s make --directory=$@

RC05_quad:
	OPTIONS=-s make --directory=$@

RC01_svd:
	OPTIONS=-s make --directory=$@

clean:
	make --directory=beta_regression clean
	make --directory=hysimple clean
	make --directory=admb_messages clean
	make --directory=init_bounded_number_matrix clean
	make --directory=betareg clean
	make --directory=gmrf clean
	make --directory=simple_mcmc clean
	make --directory=testminmax clean
	make --directory=RC04_solve clean
	make --directory=RC04_det clean
	make --directory=RC04_inv clean
	make --directory=RC10_spline1 clean
	make --directory=RC10_spline2 clean
	make --directory=RC13_dsort clean
	make --directory=RC15_eigen clean
	make --directory=RC26_dflndet clean
	make --directory=RC27_dfsolve1 clean
	make --directory=RC27_dfsolve2 clean
	make --directory=RC05_quad clean
	make --directory=RC01_svd clean
