.PHONY: clean admb_messages init_bounded_number_matrix beta_regression

all: admb_messages init_bounded_number_matrix beta_regression

admb_messages:
	OPTIONS=-s make --directory=$@

init_bounded_number_matrix:
	OPTIONS=-s make --directory=$@

beta_regression:
	OPTIONS=-s make --directory=$@

clean:
	make --directory=beta_regression clean
