run8:
	../../../admb forest8 forest-functions.cpp
	cp ../../../examples/admb/forest/forest.dat forest8.dat
	time ./forest8
clean:
	@rm -vf admodel.cov
	@rm -vf admodel.dep
	@rm -vf admodel.hes
	@rm -vf fmin.log
	@rm -vf forest8
	@rm -vf forest8.b01
	@rm -vf forest8.bar
	@rm -vf forest8.cor
	@rm -vf forest8.cpp
	@rm -vf forest8.dat
	@rm -vf forest8.eva
	@rm -vf forest8.htp
	@rm -vf forest8.log
	@rm -vf forest8.obj
	@rm -vf forest8.out
	@rm -vf forest8.p01
	@rm -vf forest8.par
	@rm -vf forest8.r01
	@rm -vf forest8.rep
	@rm -vf forest8.std
	@rm -vf forest-functions.obj
