set CYGWIN_HOME=C:\cygwin
set GNUWIN32_HOME=%ProgramFiles%\GNUWIN32
set MINGW_HOME=C:\MinGW
set INNOSETUP_HOME=%ProgramFiles%\Inno^ Setup^ 5

PATH=%GNUWIN32_HOME%\bin;%MINGW_HOME%\bin;%CYGWIN_HOME%\bin;%INNOSETUP_HOME%;%PATH%
