mforest: mforest.tpl
	ls -al ../../../admb
	PATH=../../../build/dist/bin:$PATH CXXFLAGS=-pthread LDFLAGS=-pthread admb -g mforest

run:
	-./mforest

clean:
	@rm -vf mforest
	@rm -vf variance
	@rm -vf log_slave_1
	@rm -vf log_slave_2
	@rm -vf log_master
	@rm -vf log_slave_3
	@rm -vf log_slave_4
	@rm -vf eigv.rpt
	@rm -vf log_slave_5
	@rm -vf mforest.log
	@rm -vf log_slave_6
	@rm -vf mforest.cpp
	@rm -vf log_slave_7
	@rm -vf log_slave_8
	@rm -vf log_slave_9
	@rm -vf fmin.log
	@rm -vf mforest.htp
	@rm -vf log_slave_10
	@rm -vf log_slave_11
	@rm -vf log_slave_12
	@rm -vf log_slave_13
