all:
	@make -C buscycle
	@make -C catage
	@make -C finance
	@make -C robreg
	@make -C simple
	@make -C truncreg
	@make -C vol

all2:
	@make -C forest
	@make -C chem-eng
	@make -C pella-t

clean:
	@make -C buscycle clean
	@make -C catage clean
	@make -C chem-eng clean
	@make -C finance clean
	@make -C forest clean
	@make -C pella-t clean
	@make -C robreg clean
	@make -C simple clean
	@make -C truncreg clean
	@make -C vol clean
