
RC04_solve:
	$(MAKE) --directory=$@

RC04_det:
	$(MAKE) --directory=$@

RC04_inv:
	$(MAKE) --directory=$@

RC10_spline1:
	$(MAKE) --directory=$@

RC10_spline2:
	$(MAKE) --directory=$@

RC13_dsort:
	$(MAKE) --directory=$@

RC15_eigen:
	$(MAKE) --directory=$@

RC26_dflndet:
	$(MAKE) --directory=$@

RC27_dfsolve1:
	$(MAKE) --directory=$@

RC27_dfsolve2:
	$(MAKE) --directory=$@

RC05_quad:
	$(MAKE) --directory=$@

RC01_svd:
	$(MAKE) --directory=$@
