all_au.pdf: all_au.tex
	./makeall
	./makeall

clean:
	rm -fv ttmp
	rm -fv xxx.sed
	rm -fv yyy.sed
	rm -fv all_au.pdf
	rm -fv all_au.out
	rm -fv all_au.aux
	rm -fv all_au.ind
	rm -fv all_au.idx
	rm -fv all_au.toc
	rm -fv contents.tex
	rm -fv index.tex
	rm -fv *.log
	rm -fv *.ilg

