all: expm

expm: expm.tpl
	..\..\admb expm.tpl
	expm

clean:
	if exist admodel.cov del /Q admodel.cov
	if exist admodel.dep del /Q admodel.dep
	if exist admodel.hes del /Q admodel.hes
	if exist eigv.rpt del /Q eigv.rpt
	if exist expm.bar del /Q expm.bar
	if exist expm.cor del /Q expm.cor
	if exist expm.cpp del /Q expm.cpp
	if exist expm.eva del /Q expm.eva
	if exist expm.exe del /Q expm.exe
	if exist expm del /Q expm
	if exist expm.htp del /Q expm.htp
	if exist expm.log del /Q expm.log
	if exist expm.obj del /Q expm.obj
	if exist expm.par del /Q expm.par
	if exist expm.std del /Q expm.std
	if exist fmin.log del /Q fmin.log
	if exist variance del /Q variance
