all:
	../../admb pella_t_modified
	./pella_t_modified
clean:
	@rm -vf admodel.cov
	@rm -vf admodel.dep
	@rm -vf admodel.hes
	@rm -vf fmin.log
	@rm -vf pella_t_modified
	@rm -vf pella_t_modified.b01
	@rm -vf pella_t_modified.b02
	@rm -vf pella_t_modified.b03
	@rm -vf pella_t_modified.bar
	@rm -vf pella_t_modified.cor
	@rm -vf pella_t_modified.cpp
	@rm -vf pella_t_modified.eva
	@rm -vf pella_t_modified.htp
	@rm -vf pella_t_modified.log
	@rm -vf pella_t_modified.obj
	@rm -vf pella_t_modified.p01
	@rm -vf pella_t_modified.p02
	@rm -vf pella_t_modified.p03
	@rm -vf pella_t_modified.par
	@rm -vf pella_t_modified.std
