all: f1b2vc5
	./f1b2vc5 -nohess

f1b2vc5: f1b2vc5.tpl
	../../admb ^

clean:
	rm -vf admodel.hes
	rm -vf f1b2vc5.b01
	rm -vf f1b2vc5.cor
	rm -vf f1b2vc5.htp
	rm -vf f1b2vc5.p01
	rm -vf f1b2vc5.std
	rm -vf hesscheck
	rm -vf admodel.cov
	rm -vf admodel.tmp
	rm -vf f1b2vc5.bar
	rm -vf f1b2vc5.cpp
	rm -vf f1b2vc5.log
	rm -vf f1b2vc5.par
	rm -vf hessian.bin
	rm -vf admodel.dep
	rm -vf f1b2vc5
	rm -vf f1b2vc5.bgs
	rm -vf f1b2vc5.eva
	rm -vf f1b2vc5.obj
	rm -vf f1b2vc5.rhes
	rm -vf fmin.log
