HEADERS=ecolib.h
OBJECTS=\
 Gompertz.obj\
 Hassell.obj\
 Hill.obj\
 HollingII.obj\
 HollingIII.obj\
 HollingIV.obj\
 Michaelis_Menten1.obj\
 Michaelis_Menten2.obj\
 Ricker.obj\
 Shepherd.obj\
 generalized_Ricker1.obj\
 generalized_Ricker2.obj\
 logistic.obj\
 logistic3.obj\
 logisticK.obj\
 monomolecular.obj\
 nonrectangular_hyperbola.obj\
 theta_logistic.obj

include ../admb-rules.mak
