all: cov_re

cov_re: cov_re.tpl
	..\..\admb -r cov_re.tpl
	cov_re.exe

clean:
	del admodel.cov
	del admodel.dep
	del admodel.hes
	del cov_re.bar
	del cov_re.bgs
	del cov_re.cor
	del cov_re.cpp
	del cov_re.eva
	del cov_re.exe
	del cov_re.htp
	del cov_re.log
	del cov_re.luu
	del cov_re.obj
	del cov_re.par
	del cov_re.rhes
	del cov_re.std
	del eigv.rpt
	del fmin.log
	del hesscheck
	del hessian.bin
	del variance
