verify: ham4 ham5 catage vonb vonbr n2mvol simple 

ham4:
	cd $(ADMB_HOME)\examples\admb\buscycle
	makeadm ham4
	ham4
	cd $(ADMB_HOME)\examples\admb\buscycle
	makeadms ham4
	ham4

ham5:
	cd $(ADMB_HOME)\examples\admb\buscycle
	makeadm ham5
	ham5
	cd $(ADMB_HOME)\examples\admb\buscycle
	makeadms ham5
	ham5

catage:
	cd $(ADMB_HOME)\examples\admb\catage
	makeadm catage
	catage
	cd $(ADMB_HOME)\examples\admb\catage
	makeadms catage
	catage

chem-eng:
	cd $(ADMB_HOME)\examples\admb\chem-eng
	makeadm chem-eng
	chem-eng
	cd $(ADMB_HOME)\examples\admb\chem-eng
	makeadms chem-eng
	chem-eng

finance:
	cd $(ADMB_HOME)\examples\admb\finance
	makeadm finance
	finance
	cd $(ADMB_HOME)\examples\admb\finance
	makeadms finance
	finance

forest:
	cd $(ADMB_HOME)\examples\admb\forest
	makeadm forest
	forest
	cd $(ADMB_HOME)\examples\admb\forest
	makeadms forest
	forest

pella-t:
	cd $(ADMB_HOME)\examples\admb\pella-t
	makeadm pella_t
	pella_t
	cd $(ADMB_HOME)\examples\admb\pella-t
	makeadms pella_t
	pella_t

vonb:
	cd $(ADMB_HOME)\examples\admb\robreg
	makeadm vonb
	vonb
	cd $(ADMB_HOME)\examples\admb\robreg
	makeadms vonb
	vonb

vonbr:
	cd $(ADMB_HOME)\examples\admb\robreg
	makeadm vonbr
	vonbr
	cd $(ADMB_HOME)\examples\admb\robreg
	makeadms vonbr
	vonbr


simple:
	cd $(ADMB_HOME)\examples\admb\simple
	makeadm simple
	simple
	cd $(ADMB_HOME)\examples\admb\simple
	makeadms simple
	simple

truncreg:
	cd $(ADMB_HOME)\examples\admb\truncreg
	makeadm truncreg
	runtrunc
	fruntrunc
	cd $(ADMB_HOME)\examples\admb\truncreg
	makeadms truncreg
	runtrunc
	fruntrunc

n2mvol:
	cd $(ADMB_HOME)\examples\admb\vol
	makeadm n2mvol
	n2mvol
	cd $(ADMB_HOME)\examples\admb\vol
	makeadms n2mvol
	n2mvol
