#!/bin/bash
shopt -s expand_aliases
alias help='echo -e "Usage: adcomp [-d] [-g] [-r] [-s] model\n
Compile AD Model Builder C++ to object code.\n
  -d     Create DLL
  -g     Insert debugging symbols
  -r     Create ADMB-RE
  -s     Enforce safe bounds
  model  Filename prefix, e.g. simple\n"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "-help" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi

if [ -f "$ADMB_HOME/bin/admb-cfg.sh" ]; then
  source "$ADMB_HOME/bin/admb-cfg.sh"
  CXX=$ADMB_CFG_CXX
  CXXFLAGS=$CXXFLAGS $ADMB_CFG_CXXFLAGS
else
  CXX=c++
fi

if [ "$CXX" == "openCC" ]; then
  sym=-O2
else
  sym=-O3
fi

# Pop args until model=$1
unset dll
opt=-DSAFE_ALL
while getopts "dgrs" A; do
  case $A in
    d) dll=-DBUILDING_DLL;;
    g) sym=-g;;
    r) ;;
    s) opt=-DSAFE_ALL;;
    o) opt=-DOPT_LIB;;
  esac
done
shift $((OPTIND-1))

file="${1%.*}"
if [ "`basename $file`" == "$file" ]; then
  file=$file.cpp
fi


CXXFLAGS="-c $CXXFLAGS $sym"
if [ ! -z "$dll" ]; then
  CXXFLAGS="$CXXFLAGS $dll"
fi

#if [ "$CXX" != "CC" ]; then
#  CXXFLAGS="$CXXFLAGS -Wno-deprecated"
#fi

CXXFLAGS="$CXXFLAGS -D__GNUDOS__ $dll -Dlinux $opt -DUSE_LAPLACE -I. -I\"$ADMB_HOME\"/include -I\"$ADMB_HOME\"/contrib/include"

CMD="$CXX $CXXFLAGS $file"
echo $CMD
eval $CMD

if [ $? -ne 0 ]; then
  exit 1
fi

exit 0

### r259 [2012-02-29] arnima  logged revision history
### r222 [2012-01-12] johnoel added $ADMB_HOME/contrib as include directory
### r 42 [2011-06-22] arnima  improved handling of CXXFLAGS
### r 39 [2011-06-22] johnoel improved handling of CXXFLAGS
### r982 [2010-02-16] arnima  rewrite, updated OPTIND structure, if -g then not
###                           -O3, fixed spaces, simplified echo
### r938 [2010-12-28] johnoel put CXXFLAGS before other options
### r901 [2010-12-22] johnoel moved to 'g++' dir
### r860 [2010-11-18] johnoel hardwired -O3
### r784 [2010-09-24] johnoel removed -O3
### r662 [2010-06-17] johnoel added CXXFLAGS and exit status, simplified echo
### r640 [2010-05-22] johnoel added -DSAFE_ALL
### r524 [2010-03-17] arnima  added support for filename extension like
###                           simple.cpp
### r503 [2010-02-08] johnoel split -s option into separate -g and -s options,
###                           if -g then not -O3
### r243 [2009-05-27] arnima  created
