#!/bin/bash
#
# Copyright (c) 2013 ADMB Foundation
#
shopt -s expand_aliases

if [ -f "$PWD/build/dist/bin/admb" ]; then
  declare -rx ADMB_HOME="$PWD/build/dist"
else
  if [ -f "$PWD/bin/admb" ]; then
    declare -rx ADMB_HOME="$PWD"
  fi
fi

$(ADMB_HOME)/admb $*

exit 0
