all:
	make --directory Example1
	make --directory Example2
	make --directory Example-GM

vc:
	cd Example1 && nmake
	cd Example2 && nmake
	cd Example-GM && nmake

bcc:
	cd Example1 && make
	cd Example2 && make

mingw:
	make --directory Example1 mingw
	make --directory Example2 mingw
	make --directory Example-GM mingw
