#!/bin/bash
shopt -s expand_aliases
alias help='echo -e "Usage: adcomp [-d] [-g] [-r] [-s] model\n
Compile AD Model Builder C++ to object code.\n
  -d     Create DLL
  -g     Insert debugging symbols
  -r     Create ADMB-RE
  -s     Enforce safe bounds
  model  Filename prefix, e.g. simple\n"'
if [[ "$1" == "" ]]; then help; exit; fi
if [[ "$1" == "-help" ]]; then help; exit; fi
if [[ "$1" == "--help" ]]; then help; exit; fi

# Pop args until model=$1
unset dll
g=" "
opt="-DOPT_LIB "
while getopts "dgrs" A; do
  case $A in
    d) dll="-DBUILDING_DLL ";;
    g) g="-g ";;
    r) ;;
    s) opt="-DSAFE_ALL ";;
  esac
done
shift $[OPTIND-1]

model="${1%.*}"


ARG=
if test ! -z "${CXXFLAGS}" ; then
  ARG="${CXXFLAGS} "
fi

CMD="g++ -c -O3 -Wno-deprecated ${g}${dll}${opt}-D__GNUDOS__ -Dlinux -DUSE_LAPLACE -fpermissive -I. -I$ADMB_HOME/include ${ARG}$model.cpp"
printf "%s\n" "${CMD}"
eval ${CMD}

exit 0
