name: macos-64bit-docker

on: [push]

jobs:
  build:

    runs-on: macos-14

    steps:
    - name: dist
      run: |
        brew update
        brew upgrade
        brew install --HEAD colima
        brew install docker
        colima delete
        colima start --arch x86_64
        docker pull johnoel/admb-13.2:linux-arm64
        colima stop
