name: macos-64bit-docker

on: [push]

jobs:
  build:

    runs-on: macos-14

    steps:
    - name: dist
      run: |
        brew install docker
        brew update
        brew upgrade
        colima delete
        colima start -f --arch aarch64 
        docker pull johnoel/admb-13.2:linux-arm64
