name: macos-64bit

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: clean
      run: make clean
    - name: dist
      run: |
        make
    - name: debug
      run: |
        make DEBUG=yes
    - name: shared
      run: |
        make shared
    - name: zip
      run: |
        make zip
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_macos_zip
        path: build/admb.zip
    - name: dmg
      run: |
        make ADMB_VER=admb --directory=scripts/installers/packagemaker clean all
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_dmg_distribution
        path: scripts/installers/packagemaker/ADMBTerminal.dmg
    - name: tests
      run: |
        make verify DEBUG=yes
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: outputs-opt.txt
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: adnuts_outputs.txt
        path: tests/adnuts/adnuts_outputs.txt
