name: macos-64bit

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@main
    - name: clean
      run: make clean
    - name: dist
      run: |
        make
    - name: debug
      run: |
        make DEBUG=yes
    - name: shared
      run: |
        make shared
    - name: zip
      run: |
        make zip
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_macos_zip
        path: build/admb.zip
    - name: dmg
      run: |
        make --directory=scripts/installers/packagemaker clean all
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_dmg_distribution
        path: build/admb-macos.dmg
    - name: tests
      run: |
        make --directory=tests examples SAFE_ONLY=yes
        make --directory=tests gunit-tests SAFE_ONLY=yes
        make --directory=tests outputs.txt SAFE_ONLY=yes
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: outputs.txt
    - name: kalmanfilter
      run: |
        make --directory=tests/geolocation
        cd tests/geolocation/kalmanfilter && tar cvzf trackit.tar.gz trackit
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: trackit.tar.gz
        path: tests/geolocation/kalmanfilter/trackit.tar.gz
