name: ubuntu-22.04

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@main
    - name: flex
      run: sudo apt-get install flex
    - name: clean
      run: |
        make clean
    - name: build
      run: |
        make
    - name: debug
      run: |
        make DEBUG=yes
    - name: shared
      run: |
        make shared
    - name: zip
      run: |
        make zip
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_ubuntu_zip
        path: build/admb.zip
    - name: tests 
      run: make verify DEBUG=yes TESTS_REMOTE=no
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: outputs.txt
