name: windows-vs2022-64bit

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@main
    - name: clean
      run: |
        pushd "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build" && call vcvars64.bat && popd
        nmake clean
      shell: cmd
    - name: build
      run: |
        pushd "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build" && call vcvars64.bat && popd
        nmake
        nmake shared
      shell: cmd
    - name: build g++-11
      run: |
        utilities\\make
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_vs2022
        path: build\\admb
    - name: debug
      run: |
        pushd "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build" && call vcvars64.bat && popd
        nmake DEBUG=yes
        nmake shared DEBUG=yes
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_vs2022_debug
        path: build\\admb
    - name: gtests
      run: |
        pushd "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build" && call vcvars64.bat && popd
        pushd "tests\\gtests" && nmake && popd
      shell: cmd
    - name: tests
      run: |
        pushd "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build" && call vcvars64.bat && popd
        pushd tests && nmake examples && popd
        pushd tests && nmake outputs.txt && popd
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: outputs.txt
    - name: analyze
      run: |
        pushd "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build" && call vcvars64.bat && popd
        pushd src && nmake CXXFLAGS=/analyze DEBUG=yes objects && popd
      shell: cmd
