name: windows-2019-64bit

on: [push]

jobs:
  build:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@main
    - name: clean
      run: |
        pushd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build" & call vcvars64.bat & popd
        nmake clean
      shell: cmd
    - name: build
      run: |
        pushd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build" & call vcvars64.bat & popd
        nmake
        nmake shared
      shell: cmd
    - name: build g++-8
      run: |
        utilities\\make
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_vs2019
        path: build\\admb
    - name: debug
      run: |
        pushd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build" & call vcvars64.bat & popd
        nmake DEBUG=yes
        nmake shared DEBUG=yes
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_vs2019_debug
        path: build\\admb
    - name: tests
      run: |
        pushd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build" & call vcvars64.bat & popd
        cd tests && nmake examples
        cd tests && nmake unit-gtests
        cd tests && nmake outputs.txt
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: outputs.txt
    - name: analyze
      run: |
        pushd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build" & call vcvars64.bat & popd
        cd src & nmake CXXFLAGS=/analyze DEBUG=yes objects
      shell: cmd
