name: windows-rtools42-64bit

on: [push]

jobs:
  build:

    runs-on: windows-latest 
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'release'
        rtools-version: '42'
        windows-path-include-rtools: true
    - name: clean
      run: |
        utilities\make clean SHELL=
      shell: cmd
    - name: build
      run: |
        utilities\make -j 4 SHELL=
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_rtools42
        path: build\\admb
    - name: debug
      run: |
        utilities\make -j 4 DEBUG=yes SHELL=
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: admb_rtools42_debug
        path: build\\admb
    - name: tests
      run: |
        utilities\make verify SHELL= DEBUG=yes SAFE_ONLY=yes
      shell: cmd
    - name: Artifact
      uses: actions/upload-artifact@v1
      with:
        name: outputs
        path: outputs.txt
