all: expm

expm: expm.tpl
	..\..\admb expm.tpl
	expm

clean:
	del admodel.cov
	del admodel.dep
	del admodel.hes
	del eigv.rpt
	del expm.bar
	del expm.cor
	del expm.cpp
	del expm.eva
	del expm.exe
	del expm.htp
	del expm.log
	del expm.obj
	del expm.par
	del expm.std
	del fmin.log
	del variance
