all:
	..\\..\\admb example
	example.exe

clean:
	@del /Q admodel.cov
	@del /Q admodel.dep
	@del /Q admodel.hes
	@del /Q eigv.rpt
	@del /Q example.exe
	@del /Q example.b01
	@del /Q example.bar
	@del /Q example.cor
	@del /Q example.cpp
	@del /Q example.eva
	@del /Q example.htp
	@del /Q example.log
	@del /Q example.obj
	@del /Q example.p01
	@del /Q example.par
	@del /Q example.std
	@del /Q fmin.log
	@del /Q variance
